# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: myenv

channels:
  - pytorch
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.12

  # --------- pytorch --------- #
  # Note: PyTorch 2.7 is available in conda-forge, not the official pytorch channel
  - conda-forge::pytorch=2.7.1
  - conda-forge::torchvision=0.22.1
  - conda-forge::pytorch-cuda=12.8
  - conda-forge::lightning>=2.4.0
  - conda-forge::torchmetrics>=1.3.1

  # --------- hydra --------- #
  - hydra-core=1.3*
  - conda-forge::hydra-colorlog
  - conda-forge::hydra-optuna-sweeper

  # --------- loggers --------- #
  # - wandb
  # - neptune-client
  # - mlflow
  # - comet-ml
  # - aim>=3.16.2 # no lower than 3.16.2, see https://github.com/aimhubio/aim/issues/2550

  # --------- others --------- #
  - rich=13.*
  - pre-commit=3.*
  - pytest=8.*

  - pip>=23
  - pip:
      - rootutils  # not available in conda
